unit23_dag:

  default_args:
    owner: "Alkemy_Prisma"
    start_date: 2022-11-21
    end_date: 2022-11-21
    retries: 1
    retry_delay_sec: 120
  schedule_interval: "0 * * * *"
  default_view: "tree"
  orientation: "LR"
  description: "unit20 data processing with pandas"

  tasks:

    data_extraction_task:
      operator: airflow.operators.python.PythonOperator
      python_callable_name: download_file
      python_callable_file: /home/karencaro/airflow/dags/unit23_aws_s3/src/extraction.py
      op_args:
        - /home/karencaro/airflow/dags/unit23_aws_s3/resources/medals.xlsx

    data_processing_task:
      operator: airflow.operators.python.PythonOperator
      python_callable_name: process_data
      python_callable_file: /home/karencaro/airflow/dags/unit23_aws_s3/src/processing.py
      op_args:
        - /home/karencaro/airflow/dags/unit23_aws_s3/resources/medals.xlsx
        - /home/karencaro/airflow/dags/unit23_aws_s3/resources/medals_filtered.xlsx

    data_loading_task:
      operator: airflow.operators.python.PythonOperator
      python_callable_name: upload_file
      python_callable_file: /home/karencaro/airflow/dags/unit23_aws_s3/src/loading.py
      op_args:
        - /home/karencaro/airflow/dags/unit23_aws_s3/resources/medals_filtered.xlsx
     



